version: '3.8'
services:
  app:
    build: .
    container_name: nexamart_app
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: nexamart
      MYSQL_USER: nexamart
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: